Update Configuration.php
In the 4.2 Symfony version the constructor of TreeBuilder requires to enter the name parameter.
After this modify I resolve the error  ArgumentCountError:
Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0